- name: Add docker repository key
  shell: curl https://get.docker.io/gpg | apt-key add -
  sudo: yes

- name: Add docker repository
  shell: echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
  sudo: yes

- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Install docker
  apt: pkg=lxc-docker state=installed
  sudo: yes
